### ISSUE TITLE
Make log.level a nested field to satisfy ECS spec

### ISSUE THREAD

**Issue by chrisjprior** [elastic/ecs-logging-python#48] opened 2021-07-02 08:36 UTC
I can see from the code comments that the nested property log.level created within format_to_ecs is then intentionally flattened in order to comply with the ECS schema but I haven't been able to find any reference to this in the ECS documentation, which seems to suggest that it should be a nested field.

This results in output which looks like this:
`{
"log.level": "info"
}`

instead of output which looks like this:
`{
"log: {
"level": "info"
}
}`

Can anyone point me to the relevant docs?

**Comment by sethmlarson** [comment] 2021-07-02 13:52
The reason that `log.level` is dotted like that is to make ECS more human readable. Basically the fields `@timestamp`, `log.level`, and `message` are always printed before the rest of the fields to imitate an unstructured log. A lot of unstructured logs look like this:

```
2021-07-02T01:02:03 INFO Normal log
2021-07-02T01:02:03 INFO Normal log
2021-07-02T01:02:03 ERROR Something bad happened! (...other info...)
2021-07-02T01:02:03 INFO Normal log
2021-07-02T01:02:03 INFO Normal log
```

and in ECS by favoring `@timestamp`, `log.level`, and `message` the structured log would look like this:

```
{"@timestamp":"2021-07-02T01:02:03","log.level":"INFO","message":"Normal log"}
{"@timestamp":"2021-07-02T01:02:03","log.level":"INFO","message":"Normal log"}
{"@timestamp":"2021-07-02T01:02:03","log.level":"ERROR","message":"Something bad happened!",(...other info...)}
{"@timestamp":"2021-07-02T01:02:03","log.level":"INFO","message":"Normal log"}
{"@timestamp":"2021-07-02T01:02:03","log.level":"INFO","message":"Normal log"}
```

You can also see this [encoded in the ECS spec](https://github.com/elastic/ecs-logging/blob/master/spec/spec.json), see the `index` field and the `log.level.comment` field:

```json
"fields": {
        "@timestamp": {
            "type": "datetime",
            "required": true,
            "index": 0,
            "url": "https://www.elastic.co/guide/en/ecs/current/ecs-base.html",
            "comment": [
                "Field order, as specified by 'index', is RECOMMENDED.",
                "ECS loggers must implement field order unless the logging framework makes that impossible."
            ]
        },
        "log.level": {
            "type": "string",
            "required": true,
            "index": 1,
            "comment": [
                "This field SHOULD NOT be a nested object field but at the top level with a dot in the property name.",
                "This is to make the JSON logs more human-readable.",
                "Loggers MAY indent the log level so that the `message` field always starts at the exact same offset,",
                "no matter the number of characters the log level has.",
                "For example: `'DEBUG'` (5 chars) will not be indented, whereas ` 'WARN'` (4 chars) will be indented by one space character."
            ]
        },
        "message": {
            "type": "string",
            "required": false,
            "index": 2,
            "comment": [
                "A message field is typically included in all log records, but some logging libraries allow records with no message.",
                "That's typically the case for libraries that allow for structured logging."
            ]
        },
```

Let me know if this answers your question!

**Comment by sethmlarson** [comment] 2021-07-06 17:18
Closing this as answered.

**Comment by laurivosandi** [comment] 2022-10-11 08:46
The https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html clearly states that `The document structure should be nested JSON objectsThe document structure should be nested JSON objects` so why is official Python library going against the guideline?

**Comment by basepi** [comment] 2022-10-11 20:28
It's a good question. The reality is that both are ingested the same on the elasticsearch side so the distinction is not super important.

I do think a modicum of readability is valuable, in case you ending up tailing a log on a server for some reason. This is especially true when the machine doesn't care either way.

**Comment by laurivosandi** [comment] 2022-10-11 20:31
Actually if you read next sentence in the guidelines `If you’re ingesting to Elasticsearch using the API, your fields must be nested objects, not strings containing dots` it becomes clear that ES treats them differently. It's Filebeat that does the normalization

**Comment by basepi** [comment] 2022-10-11 20:35
Good find. Probably reasonable to make this change, in that case, and not assume filebeat will fix it for us.

**Comment by felixbarny** [comment] 2022-10-12 09:28
That's right - strictly speaking, ECS loggers don't produce valid ECS documents as they use dots and nesting notation interchangeably. This is by design to improve human-readability of the logs and to make it easier and more efficient for ECS logging libraries to support arbitrary custom fields by avoiding the libraries having to maintain a map-like structure of the log event. Some of the ECS logging libraries are designed in a way where they just append all standard and custom fields to a string, without merging them into an object hierarchy. This works better when allowing dots in field names, as you can just add a key like `log.foo`, without the logger having to make sure that the `foo` key gets merged into the `log` object which makes logging more efficient.

For most purposes, it doesn't really matter as Elasticsearch also treats dots in field names the same as nested objects. However, if you do want to normalize the events, you can simply use Filebeat's `expand_keys` option (see [ecs logging docs](https://www.elastic.co/guide/en/ecs-logging/python/master/installation.html#filebeat)), or the [`dot_expander`](https://www.elastic.co/guide/en/elasticsearch/reference/current/dot-expand-processor.html) Elasticsearch ingest processor. You can see the latter in practice in the [Kibana logs integration](https://github.com/elastic/integrations/blob/main/packages/kibana/data_stream/log/elasticsearch/ingest_pipeline/pipeline-json.yml).

**Comment by basepi** [comment] 2022-10-12 17:00
After discussing this with the wider team, we've decided to keep [the `ecs_logging` spec](https://github.com/elastic/ecs-logging/blob/d3ffcf10cdb62511689fe4b595357e7d66a593b7/spec/spec.json#L25-L26) the same, and keep `log.level` as a dotted field. The Elasticsearch team is even working on an API for sending logs directly to Elasticsearch and even there, the dotted fields will not be a problem.

Thanks for the discussion!

**Closed by basepi** 2022-10-12 17:00 UTC
Labels: agent-python

**Comment by basepi** [comment] 2025-10-17 20:22
I'll leave that to @xrmx -- he's the one maintaining this repo these days.
